from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
from Modules.GenericPageActions import GenericPageActions



			LinkBack = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="startswith">Back</v>)
			LinkContinue = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Continue</v>)
			LinkEdit = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Edit</v>)
			LinkApply = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Apply</v>)
			LinkReview = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Review</v>)
			LinkGoHome = (<instance>1|<tagname>A</tagname>|<n>CLASSNAME</n><v criteria="isequalto">logoSpace</v><n>INNERTEXT</n><v criteria="contains">Home</v>)
			LinkStartOver = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Start Over</v>)
			LinkCancel = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Cancel</v>)
			LinkContinueWorking = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Continue Working</v>)
			LinkAddAnotherPerson = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Add Another Person</v>)
			LinkDeletePerson = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Delete Person</v>)
			LinkSubmit = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Submit</v>)
			LinkLogin = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Log In</v>)
			LinkSaveAndContinue = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Save and Continue</v>)
			LinkSignUp = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Sign Up</v>)
			LinkSaveAndExit = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Save and Exit</v>)
			LinkClose = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Close</v>)
			LinkSubmitApplication = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Submit Application</v>)
			LinkCancelAndExit = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Cancel and Exit</v>)
			LinkDelete = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Delete</v>)
			LinkAddAnotherEntry = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Add Another Entry</v>)
			LinkGeneric = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">REPLACEME</v>)
			LinkChevronWelcome = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Welcome</v>)
			LinkChevronStartApplication = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Start<Certify-CrLf>Application</v>)
			LinkChevronPeople = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">People</v>)
			LinkChevronJobandSchool = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Job and<Certify-CrLf>School</v>)
			LinkChevronOtherIncome = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Other<Certify-CrLf>Income</v>)
			LinkChevronExpenses = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Expenses</v>)
			LinkChevronOther = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Other</v>)
			LinkChevronSubmitApplication = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Submit<Certify-CrLf>Application</v>)
			LinkMyAccount = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">My Account</v>)
			LinkLogOut = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Log Out</v>)
			LinkExit = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Exit</v>)
			LinkSessionExpired = (<instance>1|<tagname>DIV</tagname>|<n>INNERTEXT</n><v criteria="contains">Your session has expired.</v>)
			LinkOnlineHelp = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Help  </v>)
			b'LinkLanguagePageFooter' = (b'<instance>1|<tagname>P</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Espa\xc3\xb1ol | \xe7\xb9\x81\xe9\xab\x94\xe4\xb8\xad\xe6\x96\x87 | Ti\xe1\xba\xbfng Vi\xe1\xbb\x87t | Srpsko-hrvatski | Deutsch | \xd8\xa7\xd9\x84\xd8\xb9\xd8\xb1\xd8\xa8\xd9\x8a\xd8\xa9 | \xe0\xba\x9e\xe0\xba\xb2\xe0\xba\xaa\xe0\xba\xb2\xe0\xba\xa5\xe0\xba\xb2\xe0\xba\xa7 | \xed\x95\x9c\xea\xb5\xad\xec\x96\xb4 | \xe0\xa4\xb9\xe0\xa4\xbf\xe0\xa4\x82\xe0\xa4\xa6\xe0\xa5\x80 | Fran\xc3\xa7ais | Deitsch | \xe0\xb8\xa0\xe0\xb8\xb2\xe0\xb8\xa9\xe0\xb8\xb2\xe0\xb9\x84\xe0\xb8\x97\xe0\xb8\xa2 | Tagalog | Karen | \xd0\xa0\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9</v><n>TAGNAME</n><v criteria="isequalto">P</v></findby>')
			LinkLanguageREPLACEME = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">REPLACEME</v><n>TAGNAME</n><v criteria="isequalto">A</v></findby>)
			IMGHelpinOtherLanguages = (<instance>1|<tagname>IMG</tagname>|<n>ALT</n><v criteria="isequalto">For Help in Other Languages - Call 877-347-5678</v><n>TAGNAME</n><v criteria="isequalto">IMG</v></findby>)
			IMGKarenLanguage = (<instance>1|<tagname>IMG</tagname>|<n>SRC</n><v criteria="contains">apspssp/framework/skins/APSP/iowa_images/KarenLanguage.png</v><n>TAGNAME</n><v criteria="isequalto">IMG</v></findby>)
			LinkAnswerSetError = (<instance>1|<tagname>FORM</tagname>|<n>ID</n><v criteria="isequalto">answerSet</v><n>INNERTEXT</n><v criteria="contains">REPLACEME</v></findby>)
