from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
from Modules.GenericPageActions import GenericPageActions



			TextHowMuchSocialSecurity = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			TextHowMuch RRNew = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften RRNew = (<instance>1|<tagname>SELECT</tagname>|)
			ComboSelectAPerson = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch SSD = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften SSD = (<instance>1|<tagname>SELECT</tagname>|)
			ComboHowOften SSR = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch SSR = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften SSS = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch SSS = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften RR = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch RR = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften RRD = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch RRD = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften RRS = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch RRS = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften PP = (<instance>1|<tagname>SELECT</tagname>|<n>IsHidden</n><v criteria="isequalto">False</v><n>IsVisible</n><v criteria="isequalto">True</v><n>type</n><v criteria="isequalto">select-one</v></findby>)
			TextHowMuch PP = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften DC = (<instance>1|<tagname>SELECT</tagname>|<n>IsHidden</n><v criteria="isequalto">False</v><n>IsVisible</n><v criteria="isequalto">True</v><n>className</n><v criteria="isequalto">hasScript</v></findby>)
			TextHowMuch DC = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften GE = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch GE = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften RM = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch RM = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften 401K = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch 401K = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften IRA = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch IRA = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften Annuity = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch Annuity = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften VAA = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch VAA = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften VDP = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch VDP = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
			ComboHowOften VDT = (<instance>1|<tagname>SELECT</tagname>|)
			TextHowMuch VDT = (<instance>1|<tagname>INPUT</tagname>|<n>TYPE</n><v criteria="isequalto">text</v>)
