from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
from Modules.GenericPageActions import GenericPageActions



			LinkForgotPassword/PIN = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Forgot Password/PIN</v>)
			LinkSignUp = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Sign Up</v>)
			LinkHeaderHelp = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Help</v>)
			ComboLanguage = (<instance>1|<tagname>SELECT</tagname>|<n>ID</n><v criteria="isequalto">locale</v>)
			TextHeaderUsernamePlaceholder = (<instance>1|<tagname>INPUT</tagname>|<n>ID</n><v criteria="isequalto">headerUsernamePlaceholder</v><n>TYPE</n><v criteria="isequalto">text</v>)
			PasswordHeaderPassword = (<instance>1|<tagname>INPUT</tagname>|<n>ID</n><v criteria="isequalto">headerPassword</v><n>TYPE</n><v criteria="isequalto">text</v><n>IsHidden</n><v criteria="isequalto">False</v><n>IsVisible</n><v criteria="isequalto">True</v><n>FrameId</n><v criteria="isequalto">Body</v><n>title</n><v criteria="isequalto">Password</v></findby>)
			TextHeaderPasswordPlaceholder = (<instance>1|<tagname>INPUT</tagname>|<n>ID</n><v criteria="isequalto">headerPasswordPlaceholder</v><n>TYPE</n><v criteria="isequalto">text</v>)
			LinkLogIn = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Log In</v>)
			LinkHome = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Home</v>)
			LinkAPPLYApplyforAssistance. = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Apply for assistance</v>)
			LinkCHECKWhatbenefitscouldIreceive = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">What benefits could I receive</v>)
			LinkNoticesofPrivacyPractices = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Notices of Privacy Practices</v>)
			LinkContacts = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Contacts</v>)
			LinkLegalAid = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Legal Aid</v>)
			LinkEstateRecovery = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Estate Recovery</v>)
			LinkSeniorHealthInsuranceInformationProg = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Senior Health Insurance Information Program (SHIIP)</v>)
			LinkSocialSecurity = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Social Security</v>)
			Medicare = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Medicare</v>)
			LinkPrintableApplication = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Printable Application</v>)
			LinkRegisterToVote = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Register To Vote</v>)
			LinkTermsandConditions = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Terms and Conditions</v>)
			LinkGiveUsYourFeedback = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Give Us Your Feedback</v>)
			LinkLeftHelp = (<instance>2|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Help</v>)
			LinkForTTYServices = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">For TTY Services</v>)
			TextHeaderUsername = (<instance>1|<tagname>INPUT</tagname>|<n>ID</n><v criteria="isequalto">headerUsername</v><n>TYPE</n><v criteria="isequalto">text</v>)
			LinkViewApplicationStatus = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">View application status</v><n>TAGNAME</n><v criteria="isequalto">A</v>)
			LinkWithdrawMyCompletedApplication = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Withdraw my completed application</v>)
			LinkVerifyYourIdentify = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Verify Your Identity</v>)
			LinkPasswordManagement = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Password</v><n>INNERTEXT</n><v criteria="contains">Management</v>)
			LinkSecurityQuestionsManagement = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">SecurityQuestions Management</v>)
			LinkPinManagement = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">Personal IdentificationNumber (PIN) Management</v>)
			LinkGeneric = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">REPLACEME</v>)
			LinkOpenMessageInbox = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Open</v>)
			LinkContinueSavedApplication = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Continue Saved Application</v>)
			LinkCancelIncompleteApplication = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="isequalto">Cancel my incomplete application</v>)
			LinkMyAccount = (<instance>1|<tagname>A</tagname>|<n>INNERTEXT</n><v criteria="contains">My Account</v>)
